### ISSUE TITLE
Avro Marshallers for Date and Timestamp

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/freestyle-rpc#269]
It'd be handy to have `frees-rpc` providing optional marshallers for serializing and deserializing dates, with no reference to a particular time zone or time of day.

Avro specs: https://avro.apache.org/docs/current/spec.html#Date

Initially, we could support:

#### Date

> The `date` logical type represents a date within the calendar, with no reference to a particular time zone or time of day.

#### Timestamp (millisecond precision)

> The `timestamp-millis` logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one millisecond.

As we need to take into account `Java 1.7`, we could create two new different sbt modules (artifacts):

* `frees-rpc-marshallers-jodatime`: `Java 1.7` users could include this one to serialize/deserialize dates based on:
  * Avro `date`: it can be managed by [org.joda.time.LocalDate](http://joda-time.sourceforge.net/apidocs/org/joda/time/LocalDate.html).
  * Avro `timestamp-millis`: it can be managed by [org.joda.time.LocalDateTime](http://joda-time.sourceforge.net/apidocs/org/joda/time/LocalDateTime.html).
* `frees-rpc-marshallers-javatime`: `Java +1.8` users could include this one to serialize/deserialize dates based on 
  * Avro `date`: it can be managed by [java.time.LocalDate](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html).
  * Avro `timestamp-millis`: it can be managed by [java.time.LocalDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html).

These two new modules can be placed at `modules/marshallers/jodatime` and `modules/marshallers/javatime`, respectively.

Internally, as part of the serialization/deserialization process, we can use `Long` as intermediate bytes representation.

**Comment by raulraja** [comment]
Doesn't avro4s already support `java.time.*`?

**Comment by AdrianRaFo** [comment]
Only for `LocalDate`, `LocalDateTime`

**Comment by AdrianRaFo** [comment]
Also, the avro main page specify that all the dates types supported are internally converted to an `Int|` or a `Long`

**Comment by fedefernandez** [comment]
More information:
* `pbdirect` doesn't have support for LocalDate or LocalDateTime
* `avro4s` serializes/deserializes the dates in `String` format:
https://github.com/sksamuel/avro4s/blob/a04baa577086cdba49921ec494e583da35325c21/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L73-L79
I've created a serializer/deserializer for java.time dates more aligned with the avro definition, `LocalDate` to `Int` and `LocalDateTime` to `Long`
https://github.com/frees-io/freestyle-rpc/blob/c433b6d56ca8d98eb52e3784e202f549750779d8/modules/internal/src/main/scala/util/JavaTimeUtil.scala#L23-L34

**Comment by fedefernandez** [comment]
Currently blocked by #278

**Comment by fedefernandez** [comment]
This is still blocked. I'll describe the problem in pbdirect, but the sames applies to avro.

The PR #341 defines the `PBReader` and `PBWriter` instances for the joda types `LocalDate` and `LocalDateTime`, but the service is still unable to find a `Marshaller` for case class with fields of type `LocalDate` and `LocalDateTime`. My guessing is that in the scope of this `implicit def`
https://github.com/frees-io/freestyle-rpc/blob/ed9c222b555148767b0950737cd0b7f01315bb62/modules/internal/src/main/scala/encoders.scala#L69-L77
used here
https://github.com/frees-io/freestyle-rpc/blob/0c57ad594b3081baa7b9967ac637eb3b453ac687/modules/internal/src/main/scala/service.scala#L160
the `PBReader` and `PBWriter` instances are not available, because we're importing them together with the `@service` definition.

One solution we've tried is to add the `implicit def` for the marshaller
https://github.com/frees-io/freestyle-rpc/blob/ed9c222b555148767b0950737cd0b7f01315bb62/modules/internal/src/main/scala/encoders.scala#L69-L77
in the [`jodaTimeMarshallers` object](https://github.com/frees-io/freestyle-rpc/pull/341/files#diff-0c9e289e397afefc5a4e6de0c25a851aR30) but in this case we're getting an implicit divergence.

**Comment by juanpedromoreno** [comment]
@fedefernandez @AntonioMateoGomez Do we need to do something else to complete this story? I think it might be completed after https://github.com/frees-io/freestyle-rpc/pull/373 and https://github.com/frees-io/freestyle-rpc/pull/374.

**Comment by fedefernandez** [comment]
IMO it's completed
